name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: "Name of the ressource group to be created"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_INFRA_IDENTITY_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Bicep Infrastructure
      run: |
        az deployment sub create \
          --location canadacentral \
          --template-file infra/main.bicep \
          --parameters resourceGroupName=${{ github.event.inputs.resourceGroupName }}
