name: Deploy API

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: "Name of the ressource group of the API webapp"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: dotnet build ./ResumeManagerWebApi/ResumeManagerWebApi.sln --configuration Release
      
      - name: Test
        run: dotnet test ./ResumeManagerWebApi/ResumeManagerWebApi.sln --configuration Release --no-build

      - name: Publish
        run: dotnet publish ./ResumeManagerWebApi/ResumeManagerWebApi.sln -c Release -o "${{env.DOTNET_ROOT}}/myapi"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-api
          path: ${{env.DOTNET_ROOT}}/myapi

  updateDatabase:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Restore
        run: dotnet restore ./ResumeManagerWebApi/ResumeManagerWebApi.sln
      
      - name: Login to Azure with infra-service-principal
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_INFRA_SERVICE_PRINCIPAL_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Get identity-GitHubAction clientId
        id: get-identity-clientId-updateDatabase
        run: |
          CLIENT_ID=$(az identity show \
            --name resumemanager-GitHubAction \
            --resource-group ${{ github.event.inputs.resourceGroupName }} \
            --query "clientId" -o tsv)

          echo "clientId=$CLIENT_ID" >> $GITHUB_OUTPUT

      - name: Login to Azure with api-identity
        uses: azure/login@v2
        with:
          client-id: ${{ steps.get-identity-clientId-updateDatabase.outputs.clientId }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Apply EF Core migrations
      #   env: 
      #     ConnectionStrings__DefaultConnection: "Server=tcp:resumemanager-sql.database.windows.net,1433;Initial Catalog=resumemanagerdb;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30; Authentication=\"Active Directory Managed Identity\";"
      #   run: |
      #     cd ResumeManagerWebApi
      #     dotnet ef database update

      # - name: Apply EF Core migrations
      #   env:
      #     ConnectionStrings__DefaultConnection: "Server=tcp:resumemanager-sql.database.windows.net,1433;Initial Catalog=resumemanagerdb;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=\"Active Directory Default\";"
      #   run: |
      #     cd ResumeManagerWebApi
      #     dotnet ef database update

      # - name: Get AAD token
      #   id: aad-token
      #   run: |
      #     TOKEN=$(az account get-access-token --resource https://database.windows.net --query accessToken -o tsv)
      #     echo "token=$TOKEN" >> $GITHUB_OUTPUT

      # - name: Set connection string
      #   run: |
      #     echo 'ConnectionStrings__ResumeManagerDb=Server=tcp:resumemanager-sql.database.windows.net,1433;Initial Catalog=resumemanagerdb;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=Active Directory Access Token;' >> $GITHUB_ENV

      # - name: Export SQL access token
      #   run: |
      #     echo "SQL_ACCESS_TOKEN=${{ steps.aad-token.outputs.token }}" >> $GITHUB_ENV

      # - name: Debug env
      #   run: printenv | sort

      # - name: EF Core info
      #   run: |
      #     cd ResumeManagerWebApi
      #     dotnet ef dbcontext info

      # - name: Apply EF Core migrations
      #   run: |
      #     cd ResumeManagerWebApi
      #     dotnet ef database update --context ResumeManagerDbContext --startup-project . --project .

      # - name: Apply EF Core migrations
      #   run: |
      #     cd ResumeManagerWebApi
      #     dotnet ef database update \
      #       --context ResumeManagerDbContext \
      #       --connection "Server=tcp:resumemanager-sql.database.windows.net,1433;Initial Catalog=resumemanagerdb;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

      - name: Get AAD token
        id: aad-token
        run: |
          TOKEN=$(az account get-access-token --resource https://database.windows.net --query accessToken -o tsv)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Export SQL access token
        run: |
          echo "SQL_ACCESS_TOKEN=${{ steps.aad-token.outputs.token }}" >> $GITHUB_ENV
      
      - name: Dump token claims
        run: |
          TOKENN=$(az account get-access-token --resource https://database.windows.net --query accessToken -o tsv)
          echo $TOKENN | jq -R 'split(".") | .[1] | @base64d | fromjson'

      - name: Apply EF Core migrations
        env:
          SQL_ACCESS_TOKEN: ${{ steps.aad-token.outputs.token }}
          ConnectionStrings__ResumeManagerDb: "Server=tcp:resumemanager-sql.database.windows.net,1433;Initial Catalog=resumemanagerdb;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        run: |
          cd ResumeManagerWebApi
          dotnet ef database update

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-api
      
      - name: Login to Azure with infra-service-principal
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_INFRA_SERVICE_PRINCIPAL_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get identity-GitHubAction clientId
        id: get-identity-clientId-deploy
        run: |
          CLIENT_ID=$(az identity show \
            --name resumemanager-GitHubAction \
            --resource-group ${{ github.event.inputs.resourceGroupName }} \
            --query "clientId" -o tsv)

          echo "clientId=$CLIENT_ID" >> $GITHUB_OUTPUT
      
      - name: Login to Azure with api-identity
        uses: azure/login@v2
        with:
          client-id: ${{ steps.get-identity-clientId-deploy.outputs.clientId }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'resumemanager-api'
          ResourceGroupName: ${{ github.event.inputs.resourceGroupName }}
          slot-name: 'Production'
          package: .
          