# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ResumeManager Api

on:
  push:
    branches:
      - main
    paths: 
      - 'ResumeManagerWebApi/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: dotnet build ./ResumeManagerWebApi/ResumeManagerWebApi.sln --configuration Release
      
      - name: Test
        run: dotnet test ./ResumeManagerWebApi/ResumeManagerWebApi.sln --configuration Release --no-build

      - name: Publish
        run: dotnet publish ./ResumeManagerWebApi/ResumeManagerWebApi.sln -c Release -o "${{env.DOTNET_ROOT}}/myapi"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-api
          path: ${{env.DOTNET_ROOT}}/myapi

  updateDatabase:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Restore
        run: dotnet restore ./ResumeManagerWebApi/ResumeManagerWebApi.sln

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_RESUMEMANAGER_GITHUBACTIONS }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Apply EF Core migrations
        env: 
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING_RESUMEMANAGER }}
        run: |
          cd ResumeManagerWebApi
          dotnet ef database update

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-api
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C4822219C5C14FE88F8EDAF50B84AD7C }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ResumeManagerAPI'
          slot-name: 'Production'
          package: .
          